steps:
- name: gcr.io/cloud-builders/docker
  args: [
   'build', 
   '-t', 
   'gcr.io/cloudasset-358015/priyanka:$SHORT_SHA',
   '.'
  ]
- name: gcr.io/cloud-builders/docker
  args: [
   'push', 
   'gcr.io/$PROJECT_ID/priyanka:$SHORT_SHA'
  ]
#step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=barath-cluster'
#step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment', 
   'helloweb', 
   'hello-app=gcr.io/cloudasset-358015/priyanka:$SHORT_SHA'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=barath-cluster'
# push images to Google Container Registry with tags
images: [
   'gcr.io/cloudasset-358015/priyanka:$SHORT_SHA'
  ] 
